@url = "http://localhost:3000/"

GET http://localhost:3000/flights HTTP/1.1

###
GET http://localhost:3000/flights/id HTTP/1.1

###
POST http://localhost:3000/flights HTTP/1.1
Content-Type: "application/json"

{
    "title": " Janet",
    "time": "10am",
    "price":"300000",
    "date": "20-2-2023"
}

###
PUT http://localhost:3000/flights HTTP/1.1
Content-Type: "application/json"

{
    "title": " Moromoke",
    "time": "11am",
    "price":"500000",
    "date": "20-12-2022"
}

###
DELETE http://localhost:3000/Flight/ HTTP/1.1
